export const CHANGE_INPUT='REGISTER/CHANGE_INPUT';
export const LOGIN_SUCCESS='LOGIN/REGISTER_SUCCESS';
export const ERROR_MESSAGE='REGISTER/ERROR_MESSAGE';
export const LOAD_DATA='REGISTER/LOAD_DATA';
